### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ywbae** [ywbae/furima_28863#11]
# URL
https://furima-28863.herokuapp.com/

# 認証
ID : admin
PW : 2222

# 出品者用アカウント
ID : selling@abc.com
PW : selling123

# 購入者用アカウント
ID : buying@abc.com
PW : buying123

# 購入用カードの番号・期限・セキュリティコード
カード番号：4242424242424242
期限：2 / 22 （未来）
セキュリティコード：123

**Comment by tech-oa** [comment]
ywbaeさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]

> 正しいクレジットカードの情報で無い場合は、決済できない

購入出来てしまいます。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by ywbae** [comment]
ご確認ありがとうございます！
「正しいクレジットカードの情報で無い場合は、決済できない」とご指摘いただきましたが、私の方でもう一度確認したところ、テストコード以外のカード情報を入れた場合、決済には進みませんでした。
例えば、1234123412341234 のようなカード番号でも決済が進んだという認識であってますでしょうか？

https://pay.jp/docs/testcard

上記、payjpで提示する、トークンを作成するテストカードのみで決済が進められるかと思います。
お手数お掛け致しますが、再度ご確認をお願いできますでしょうか？

カード情報を確認することは、完全に payjp 側の機能だと認識しており、どこにバリデーションをつけるべきか、もしくは、そもそもエディタ上でバリデーションはつけられないんじゃないかと考えております。

**Comment by tech-oa** [comment]
ywbaeさん、返信有り難うございます。

> 「正しいクレジットカードの情報で無い場合は、決済できない」

こちらに関して、再度挙動を確認してみたところ、問題なく購入できました。大変申し訳ありませんでした。

他の機能に関しても挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
※また、購入ボタンを押したのち、一瞬入力情報がリセットされ、トップページに遷移しています。ユーザーの目線で考えた場合、購入ボタンからすぐにトップページに遷移した方が使いやすいと思います。もしお時間がありましたら、その点の修正にも挑戦してみていただければと思います。
